[versions]
# libs
coreKtxVersion = "1.10.1"
appcompatVersion = "1.6.1"
materialVersion = "1.9.0"
composeBomVersion = "2023.08.00"
activityComposeVersion = "1.7.2"
lifecycleComposeVersion = "2.6.2"
navVersion = "2.7.1"
hiltVersion = "2.48"
hiltNavComposeVersion = "1.0.0"
roomVersion = "2.5.2"
retrofitVersion = "2.9.0"
okHttpVersion = "4.2.1"
gsonVersion = "2.10.1"
timberVersion = "5.0.1"
desugarLibsVersion = "2.0.3"
junitVersion = "4.13.2"
coroutinesTestVersion = "1.7.1"
mockitoKotlinVersion = "3.2.0"
hamcrestVersion = "2.2"
androidxJunitExtVersion = "1.1.5"
espressoVersion = "3.5.1"

# plugins
androidGradlePluginVersion = "8.9.1"
kotlinVersion = "1.9.24"
kspVersion = "1.9.24-1.0.20"


[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
google-material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

# Compose Extra
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleComposeVersion"  }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleComposeVersion" }

# Navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }

# Hilt
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
hilt-nav-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavComposeVersion" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

# Network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofitVersion" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }

# Misc
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
desugar-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarLibsVersion" }

# Testing
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTestVersion" }
# TODO [23-10-12 10:32p.m.] -- mockito-kotlin latest requires java 11 support.
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrestVersion" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttpVersion" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunitExtVersion" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePluginVersion" }
jetbrains-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }